新規投稿機能の実装
kentoyoshioka/tenkue-board-r016 pull request #2
Opened 2020-12-31 06:34 UTC by kentoyoshioka

# 変更の目的
ログイン済のユーザーが新規投稿できるようにするため

# 達成条件

- [ ] 投稿内容が必須になっている

- [ ] 投稿内容は140字以内

- [ ] バリデーション違反した際にエラーメッセージが表示される

- [ ] エラーメッセージが日本語化している

- [ ] ログインしていない状況で投稿画面にアクセスできないようになっている

# レビュー完了希望日
レビュー完了希望日時は以下の通りです。
・2021年1月3日(日曜日)18:00まで
お忙しい中恐れ入りますが、何卒よろしくお願いいたします🙇‍♂️

2021-01-02 16:16 UTC, yutaro48 reviewed
機能実装お疲れ様です🙇‍♂️
１点修正希望があります。
おそらく動作自体には影響はないと思うのですが、念のため確認をお願いしたいです！

2021-01-02 16:16 UTC, yutaro48 commented on app/controllers/posts_controller.rb
> +  end
### 修正希望
[IMO] 僕だったら、13行目 createアクション内のcreateメソッドをnewメソッドにするかもしれません。

### 理由
createメソッドにはnewメソッドとsaveメソッドが内包されており、後述if文内のsaveメソッドと重複してしまうのではないかと考えたからです。

### 提案
13行目のcreateメソッドをnewメソッドに書き換えるのはいかがでしょうか。

2021-01-03 08:20 UTC, akane4116 commented
お疲れ様です。
確認させていただきました。こちらから申し上げることはありません。
ありがとうございます！

2021-01-03 10:32 UTC, kentoyoshioka commented on app/controllers/posts_controller.rb
> +  end
posts_controller の create アクションを build へ修正致しました。
ご指摘ありがとうございました！

2021-01-03 10:50 UTC, yutaro48 commented on app/controllers/posts_controller.rb
> +  end
ご対応ありがとうございます🙇‍♂️
たしかにbuildメソッドの使用がベストだと思います！
LGTMです！

2021-01-04 12:00 UTC, sew-sou19 requested changes
レビュー完了しました！
ご確認＆修正お願いしますー！

2021-01-04 13:50 UTC, kentoyoshioka commented on app/controllers/application_controller.rb
> +  end
機能を確認する際に初めのユーザーを取ってくる様に設定していたのを削除するのを忘れておりました。
削除しておきます！

2021-01-04 13:54 UTC, kentoyoshioka commented on app/models/post.rb
> +  belongs_to :user, dependent: :destroy
> ここでdependent: :destroyをつけてる意味はなんでしょうかー？

post modelにもつける必要があると勘違いしておりました、削除しておきます！

2021-01-04 14:04 UTC, kentoyoshioka commented on config/routes.rb
> -  root to: 'posts#index'
> rootパスは必ず設定しましょうー！
> これだと、�/にアクセスした際に、「Yay! Rails」の画面になってしまうかと思います。。。

そうですね、そこを考えずに削除しておりました
修正しておきます！

2021-01-04 14:40 UTC, sew-sou19 commented on app/models/post.rb
> +  belongs_to :user, dependent: :destroy
ですね！
`dependent: :destroy`は、親モデルを削除したときに、紐づく小モデルも同時に削除する、というイメージです！

2021-01-04 14:41 UTC, sew-sou19 approved these changes
LGTMですー！

2021-01-05 04:08 UTC, merged