掲示板編集/削除機能の実装
kentoyoshioka/tenkue-board-r016 pull request #6
Opened 2021-01-08 01:46 UTC by yutaro48

# 変更の目的
掲示板を編集/削除できるようにするため

# 達成条件

- [ ] 投稿者内容を変更することができる
- [ ] 掲示板を削除することができる
- [ ] 掲示板を編集・削除できるのは投稿者のみ
- [ ] 投稿者だけが編集ページに遷移できる
- [ ] 新規投稿時と同じUIで編集機能を実装している
- [ ] 編集画面を開いた時点で、既に登録されている投稿内容が表示されている
- [ ] 投稿内容が必須になっている
- [ ] バリデーションに反した際に、エラーメッセージが表示される
- [ ] 未ログイン時には投稿編集画面にアクセスできないようになっている

# 条件達成のために行った変更の内容

- [ ] postsコントローラにedit/update/deleteアクションを定義
>[update]  app/controllers/posts_controller.rb
- [ ] 編集表示画面の作成
>[add]  app/views/posts/edit.html.erb
- [ ] 新規投稿画面の修正
>[update]  app/views/posts/new.html.erb
- [ ] フォームの部分テンプレートの作成
>[add]  app/views/posts/_form.html.erb
- [ ] 詳細表示画面にリンクの貼り付け
>[update]  app/views/posts/show.html.erb

# レビュー完了希望日（メンバー）
レビュー完了希望日時は以下の通りです。
・2020年1月8日(金曜日)22:00まで
短納期で申し訳ございません🙇‍♂️
お忙しい中恐れ入りますが、何卒よろしくお願いいたします🙇‍♂️

2021-01-08 14:09 UTC, kentoyoshioka commented
LGTMです！

2021-01-09 05:07 UTC, sew-sou19 requested changes
ほぼ問題ないです！
部分テンプレートも良いですね。一部だけご確認と修正をお願いしますー！

2021-01-09 05:07 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @posts = current_user.posts.find(params[:id])
ここは`set_post`があるので、利用しましょう！

2021-01-09 05:07 UTC, sew-sou19 commented on app/controllers/posts_controller.rb
> +    @post = current_user.posts.find(params[:id])
ここもですね！

2021-01-10 06:10 UTC, sew-sou19 approved these changes
LGTMですー！

2021-01-10 08:23 UTC, merged